version: 2.1

aliases:
  - &restore_yarn_cache
    restore_cache:
      name: Restore yarn cache
      keys:
        - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - yarn-packages-v1-{{ .Branch }}-
        - yarn-packages-v1-
  - &yarn_install
    run:
      name: Install dependencies
      command: yarn --frozen-lockfile

jobs:
  setup:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Nodejs Version
          command: node --version
      - *restore_yarn_cache
      - *yarn_install
      - save_cache:
          name: Save yarn cache
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

  lint:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - run:
          name: Lint
          command: mkdir -p reports/junit && yarn lint --custom-formatter node_modules/stylelint-junit-formatter -o reports/junit/stylelint-results.xml
      - store_test_results:
          path: reports/junit

  build:
    docker:
      - image: circleci/ruby:latest-node-browsers
    steps:
      - checkout
      - run:
          name: Install Jekyll
          command: gem install jekyll
      - run:
          name: Build
          command: jekyll build
          when: always
      - persist_to_workspace:
          root: .
          paths:
            - _site

  lighthouse:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - attach_workspace:
          at: _site
      - run:
          name: Install Jekyll
          command: yarn http-server -p 8000 -o -S _site
      - run:
          name: Install lighthouse
          command: yarn global add @lhci/cli
      - run:
          name: Run lighthouse
          command: lhci autorun

workflows:
  default:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - setup
