name: main
on:
  push:
    branches:
      - master
jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
  check:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Check Format
            task: yarn format:check
          - name: Lint
            task: yarn lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: ${{ matrix.task }}
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - run: gem install jekyll
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - uses: actions/download-artifact@v2
        with:
          name: site
      - run: yarn add @lhci/cli
      - run: yarn lhci autorun
